#!/usr/bin/env bash
# Transfers a file from our client to a server.
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if [ $# -lt 4 ]; then
    usage
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "FILE_PATH" "USERNAME@$SERVER_IP:~/"
