#!/usr/bin/env bash
# Update package lists
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"
echo "Hello World!" > /var/www/html/index.html
NGINX_CONF="/etc/nginx/sites-available/default"
cp $NGINX_CONF ${NGINX_CONF}.bak
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 '"$REDIRECT_URL"';\n\t}\n' $NGINX_CONF
service nginx start