#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"
echo "Hello World!" > /var/www/html/index.html
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 '"$REDIRECT_URL"';\n\t}\n' /etc/nginx/sites-available/default
service nginx start
