#!/usr/bin/env bash
# script that restores the default server port

serv="listen 8080 default_server;"
new="listen 80 default_server;"
sudo sed -i "s/$serv/$new/" /etc/nginx/sites-enabled/default
sudo sed -i "22d" /etc/nginx/sites-enabled/default
sudo service nginx restart
