#!/usr/bin/env bash
# Update the package list and install Nginx
apt-get update
apt-get install -y nginx

# Ensure Nginx is configured to listen on port 80
ufw allow 'Nginx HTTP'
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration
sudo service nginx restart
