#!/usr/bin/env bash
# Displays numbers from 1 to 20, displays bad luck from China for the 4th iteration,
#+ bad luck from Japan for the 9th loop iteration, and bad luck from Italy for the 17th iteration
i=1

while [ $i -le 20 ]
do
   echo "$i"
   if [ $i -eq 4 ]
   then
    echo "bad luck from China"
    elif [ $i -eq 9 ]
    then
    echo "bad luck from Japan"
    elif [ $i -eq 17 ]
    then
    echo "bad luck from Italy"
    fi
    ((i++))
done