#!/usr/bin/env bash
#Configures Ubuntu server with localhost to 127.0.0.2, facebook.com - 8.8.8.8
cp /etc/hosts /etc/hosts.backup
sed -i '/127.0.0.1\s\+localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts